In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris.csv to iris.csv

In [ ]:
import pandas as pd
import numpy as np
dataframe = pd.read_csv('iris.csv', dtype='str', header=0, names=['slength', 'swidth', 'plength', 'pwidth', 'spieces'])

In [ ]:
dataframe

    slength swidth plength pwidth         spieces
0       4.9    3.0     1.4    0.2     Iris-setosa
1       4.7    3.2     1.3    0.2     Iris-setosa
2       4.6    3.1     1.5    0.2     Iris-setosa
3       5.0    3.6     1.4    0.2     Iris-setosa
4       5.4    3.9     1.7    0.4     Iris-setosa
..      ...    ...     ...    ...             ...
144     6.7    3.0     5.2    2.3  Iris-virginica
145     6.3    2.5     5.0    1.9  Iris-virginica
146     6.5    3.0     5.2    2.0  Iris-virginica
147     6.2    3.4     5.4    2.3  Iris-virginica
148     5.9    3.0     5.1    1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
pd.set_option('display.max_rows', 10)

In [ ]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   slength  149 non-null    object
 1   swidth   149 non-null    object
 2   plength  149 non-null    object
 3   pwidth   149 non-null    object
 4   spieces  149 non-null    object
dtypes: object(5)
memory usage: 5.9+ KB

In [ ]:
dataframe_slice = dataframe[0:20]

In [ ]:
dataframe_slice

   slength swidth plength pwidth      spieces
0      4.9    3.0     1.4    0.2  Iris-setosa
1      4.7    3.2     1.3    0.2  Iris-setosa
2      4.6    3.1     1.5    0.2  Iris-setosa
3      5.0    3.6     1.4    0.2  Iris-setosa
4      5.4    3.9     1.7    0.4  Iris-setosa
..     ...    ...     ...    ...          ...
15     5.4    3.9     1.3    0.4  Iris-setosa
16     5.1    3.5     1.4    0.3  Iris-setosa
17     5.7    3.8     1.7    0.3  Iris-setosa
18     5.1    3.8     1.5    0.3  Iris-setosa
19     5.4    3.4     1.7    0.2  Iris-setosa

[20 rows x 5 columns]

In [ ]:
dataframe.describe()

       slength swidth plength pwidth          spieces
count      149    149     149    149              149
unique      35     23      43     22                3
top        5.0    3.0     1.5    0.2  Iris-versicolor
freq        10     26      14     27               50

In [ ]:
# Write your code here
url = 'https://www.covid19.admin.ch/api/data/20210823-4c27ic5b/sources/COVID19VaccPersons_v2.json'
# url = 'https://www.covid19.admin.ch/api/data/20230815-7ixiby4u/sources/COVID19Death_geoRegion_sex_w.csv'
df = pd.read_csv(url)
df

In [ ]:
dataframe.iat[0,-1] = 'Iris-setosa'

# loc or iloc

In [ ]:
dataframe

    slength swidth plength pwidth         spieces
0       4.9    3.0     1.4    0.2     Iris-setosa
1       4.7    3.2     1.3    0.2     Iris-setosa
2       4.6    3.1     1.5    0.2     Iris-setosa
3       5.0    3.6     1.4    0.2     Iris-setosa
4       5.4    3.9     1.7    0.4     Iris-setosa
..      ...    ...     ...    ...             ...
144     6.7    3.0     5.2    2.3  Iris-virginica
145     6.3    2.5     5.0    1.9  Iris-virginica
146     6.5    3.0     5.2    2.0  Iris-virginica
147     6.2    3.4     5.4    2.3  Iris-virginica
148     5.9    3.0     5.1    1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
dataframe.loc[4:10,'plength']

4     1.7
5     1.4
6     1.5
7     1.4
8     1.5
9     1.5
10    1.6
Name: plength, dtype: object

In [ ]:
dataframe.iloc[4:10,1:3]

  swidth plength
4    3.9     1.7
5    3.4     1.4
6    3.4     1.5
7    2.9     1.4
8    3.1     1.5
9    3.7     1.5

In [ ]:
dataframe['spieces']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: spieces, Length: 149, dtype: object

In [ ]:
dataframe[0:3]

  slength swidth plength pwidth      spieces
0     4.9    3.0     1.4    0.2  Iris-setosa
1     4.7    3.2     1.3    0.2  Iris-setosa
2     4.6    3.1     1.5    0.2  Iris-setosa

In [ ]:
dataframe['spieces'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
dataframe[dataframe['spieces']=='Iris-setosa']

   slength swidth plength pwidth      spieces
0      4.9    3.0     1.4    0.2  Iris-setosa
1      4.7    3.2     1.3    0.2  Iris-setosa
2      4.6    3.1     1.5    0.2  Iris-setosa
3      5.0    3.6     1.4    0.2  Iris-setosa
4      5.4    3.9     1.7    0.4  Iris-setosa
..     ...    ...     ...    ...          ...
44     4.8    3.0     1.4    0.3  Iris-setosa
45     5.1    3.8     1.6    0.2  Iris-setosa
46     4.6    3.2     1.4    0.2  Iris-setosa
47     5.3    3.7     1.5    0.2  Iris-setosa
48     5.0    3.3     1.4    0.2  Iris-setosa

[49 rows x 5 columns]

vector operations

In [ ]:
dataframe.iloc[:,0:4] = dataframe.iloc[:,0:4].astype(float)

In [ ]:
dataframe['half slenght'] = dataframe['slength']/2.

In [ ]:
grouped_by_spiecie = dataframe.groupby('spieces')

In [ ]:
grouped_by_spiecie.size

In [ ]:
dataframe.sort_values(['slength', 'swidth'], ascending=[False, True])

     slength swidth plength pwidth         spieces  half slenght
130      7.9    3.8     6.4    2.0  Iris-virginica          3.95
117      7.7    2.6     6.9    2.3  Iris-virginica          3.85
121      7.7    2.8     6.7    2.0  Iris-virginica          3.85
134      7.7    3.0     6.1    2.3  Iris-virginica          3.85
116      7.7    3.8     6.7    2.2  Iris-virginica          3.85
..       ...    ...     ...    ...             ...           ...
40       4.5    2.3     1.3    0.3     Iris-setosa          2.25
7        4.4    2.9     1.4    0.2     Iris-setosa          2.20
37       4.4    3.0     1.3    0.2     Iris-setosa          2.20
41       4.4    3.2     1.3    0.2     Iris-setosa          2.20
12       4.3    3.0     1.1    0.1     Iris-setosa          2.15

[149 rows x 6 columns]

In [ ]:
dataframe[(dataframe['slength']>=5.)]

     slength swidth plength pwidth         spieces  half slenght
3        5.0    3.6     1.4    0.2     Iris-setosa          2.50
4        5.4    3.9     1.7    0.4     Iris-setosa          2.70
6        5.0    3.4     1.5    0.2     Iris-setosa          2.50
9        5.4    3.7     1.5    0.2     Iris-setosa          2.70
13       5.8    4.0     1.2    0.2     Iris-setosa          2.90
..       ...    ...     ...    ...             ...           ...
144      6.7    3.0     5.2    2.3  Iris-virginica          3.35
145      6.3    2.5     5.0    1.9  Iris-virginica          3.15
146      6.5    3.0     5.2    2.0  Iris-virginica          3.25
147      6.2    3.4     5.4    2.3  Iris-virginica          3.10
148      5.9    3.0     5.1    1.8  Iris-virginica          2.95

[127 rows x 6 columns]

In [ ]:
dataframe[(dataframe['slength']>=5.)].to_csv('/content/drive/MyDrive/myout.csv')